/* (C) Copyright 1993 Minas E. Spetsakis. All rights reserved. */

/* YOU CANNOT USE, DISTRIBUTE, MODIFY MEDIAMATH SOFTWARE WITHOUT */
/* WRITTEN PERMISSION BY THE AUTHOR. THE SOFTWARE IS PROVIDED ON A AS */
/* IS BASIS WITHOUT ANY WARRANTIES EXPRESS OR IMPLIED ON MERCHANTABLITY */
/* OR SUITABILITY FOR ANY APPLICATION. THE AUTHOR ASSUMES NO RESPONSIBILITY */
/* FOR DAMAGE, DIRECT OR CONSEQUENTIAL RESULTING FROM THE USE OF THIS */
/* SOFTWARE. */ 

/*

Headers for ordinary functions

*/

